// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxHRBUWrxMVjvkW2ufQtdtGImUauJCeoI',
    appId: '1:268611426289:android:d51dcc4ab84508120f1650',
    messagingSenderId: '268611426289',
    projectId: 'habilog',
    databaseURL: 'https://habilog-default-rtdb.firebaseio.com',
    storageBucket: 'habilog.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBc9BE7yx-LtKycOmU8C7Z6RlqQSN1fVHA',
    appId: '1:268611426289:ios:b9230773fef1a7ba0f1650',
    messagingSenderId: '268611426289',
    projectId: 'habilog',
    databaseURL: 'https://habilog-default-rtdb.firebaseio.com',
    storageBucket: 'habilog.appspot.com',
    iosClientId: '268611426289-tr1g6l6nrhb66ajh1ht0opfjkbfgdv8e.apps.googleusercontent.com',
    iosBundleId: 'com.example.dontKillOurPlant',
  );
}
